[package]
name = "rtr_tutorial"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["phong"]

[dependencies]
pollster = "0.3.0"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
