[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
env_logger = "0.11.5"
instant = "0.1.13"
log = "0.4.22"
wgpu = "22.1.0"
winit = { version = "0.29", features = ["rwh_05"] }
